dependencies:
  - python=3.8.5
  - jupyterlab=2.1.5
  - matplotlib=3.3.2
  - numpy=1.19.2
  - pandas=1.1.3
  - requests=2.24.0
  - seaborn=0.11.0
  - coverage=5.3
  - flake8=3.8.4
  - python-dateutil=2.8.1
  - requests=2.24.0
  - responses=0.12.1