# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python

name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Test
      run: |
        $CONDA/bin/coverage run -m unittest discover -s tests
    - name: Lint with flake8
      run: |
        $CONDA/bin/flake8 .